### ISSUE TITLE
Provide eclipse-commons library at maven central

### ISSUE THREAD

**Issue by de-jcup** [de-jcup/eclipse-commons#30]
https://github.com/de-jcup/eclipse-commons must be available  at https://repo1.maven.org/maven2/de/jcup/eclipse-commons

as done for ASP with https://github.com/de-jcup/asp/issues/30.

**Comment by de-jcup** [comment]
@vogella: Thank you for the issue. 

For  https://github.com/de-jcup/eclipse-commons/issues/30 which is necessary for 
- https://github.com/de-jcup/eclipse-asciidoctor-editor/issues/373 and 
- https://github.com/de-jcup/eclipse-asciidoctor-editor/issues/371 and
- having here multiple eclipse dependencies which are not build by gradle, 
I think this absolutely necessary.

It would be great if you could also help to migrate this to maven Tycho.

**Comment by vogella** [comment]
What is missing here? Only the publishing part to Maven central? I never did that but it sounds easy https://bjansen.github.io/java/2021/02/03/deploying-to-maven-central-using-github-actions.html

IMO it would be great if the library can be automatically published.

**Comment by vogella** [comment]
@de-jcup I think https://bjansen.github.io/java/2021/02/03/deploying-to-maven-central-using-github-actions.html would be the next step to continue the build work
