### ISSUE TITLE
Convert to Maven build

### ISSUE THREAD

**Issue by vogella** [de-jcup/eclipse-commons#31]
Do you also have plans to convert this to a Maven build?

**Comment by de-jcup** [comment]
@vogella: Thank you for the issue.

For  https://github.com/de-jcup/eclipse-commons/issues/30 which is necessary for 
- https://github.com/de-jcup/eclipse-asciidoctor-editor/issues/373 and 
- https://github.com/de-jcup/eclipse-asciidoctor-editor/issues/371 and
- having here multiple eclipse dependencies which are not build by gradle, 
I think this absolutely necessary.
