### ISSUE TITLE
Move commons to Java 11

### ISSUE THREAD

**Issue by vogella** [de-jcup/eclipse-commons#33]
Java 8 is dead. Can we move this plug-in to Java 11?

**Comment by de-jcup** [comment]
With #30 we will provide 1.0.0 with Java 8 at maven central. After this with https://github.com/de-jcup/eclipse-commons/milestone/13 (1.1.0) the step to Java 11 will be done. So at least one "old" version for java 8  is available at maven central.

**Comment by de-jcup** [comment]
Was done with 65ec11a31c8fa2c9fb1438be9abebe3c1cf3b64d
